"""Generate a runnable quantitative-research project skeleton."""

from __future__ import annotations

import argparse
import textwrap
from pathlib import Path

import yaml

FOLDERS = (
    "data/raw",
    "data/processed",
    "logs",
    "models/trained",
    "modules",
    "notebooks",
    "pipelines",
    "reports",
    "tests",
)

PIPELINE_MODULES = (
    "pipelines.train_pipeline",
    "pipelines.backtest_pipeline",
)

PIPELINE_TEMPLATE = textwrap.dedent(
    """\
    import argparse


    def main() -> None:
        parser = argparse.ArgumentParser(description={description!r})
        parser.parse_args()
        print({message!r})


    if __name__ == "__main__":
        main()
    """
)

FULL_PIPELINE_TEMPLATE = textwrap.dedent(
    """\
    import argparse
    import subprocess
    import sys
    from pathlib import Path

    import yaml


    def main() -> None:
        parser = argparse.ArgumentParser(description="Run configured pipeline modules")
        parser.add_argument("--config", default="config.yaml")
        args = parser.parse_args()

        project_root = Path(__file__).resolve().parents[1]
        with (project_root / args.config).open() as config_file:
            config = yaml.safe_load(config_file) or {}

        for module in config.get("pipelines", []):
            subprocess.run(
                [sys.executable, "-m", module],
                cwd=project_root,
                check=True,
            )


    if __name__ == "__main__":
        main()
    """
)

README_TEMPLATE = textwrap.dedent(
    """\
    # Quant Research Project

    Generated by `project_scaffold.py`.

    ```bash
    python -m pipelines.full_pipeline
    ```
    """
)

DOCKERFILE_TEMPLATE = textwrap.dedent(
    """\
    FROM python:3.11-slim
    WORKDIR /app
    COPY requirements.txt .
    RUN pip install --no-cache-dir -r requirements.txt
    COPY . .
    CMD ["python", "-m", "pipelines.full_pipeline"]
    """
)


def _module_path(root: Path, module: str) -> Path:
    return root.joinpath(*module.split(".")).with_suffix(".py")


def create_structure(root: str | Path) -> Path:
    """Create a scaffold whose configured pipeline modules all exist and run."""
    project_root = Path(root).expanduser().resolve()
    if project_root.exists() and any(project_root.iterdir()):
        raise FileExistsError(f"Refusing to overwrite non-empty directory: {project_root}")

    for folder in FOLDERS:
        (project_root / folder).mkdir(parents=True, exist_ok=True)

    for package in ("modules", "pipelines", "tests"):
        (project_root / package / "__init__.py").touch()

    pipeline_details = {
        "pipelines.train_pipeline": ("Train model pipeline", "Training pipeline placeholder"),
        "pipelines.backtest_pipeline": (
            "Backtest strategy pipeline",
            "Backtest pipeline placeholder",
        ),
    }
    for module in PIPELINE_MODULES:
        description, message = pipeline_details[module]
        _module_path(project_root, module).write_text(
            PIPELINE_TEMPLATE.format(description=description, message=message)
        )

    (project_root / "pipelines" / "full_pipeline.py").write_text(FULL_PIPELINE_TEMPLATE)

    config = {
        "project_root": ".",
        "data": {"raw": "data/raw", "processed": "data/processed"},
        "models": {"trained": "models/trained"},
        "pipelines": list(PIPELINE_MODULES),
    }
    (project_root / "config.yaml").write_text(yaml.safe_dump(config, sort_keys=False))
    (project_root / "requirements.txt").write_text("pyyaml>=6.0\n")
    (project_root / "README.md").write_text(README_TEMPLATE)
    (project_root / "Dockerfile").write_text(DOCKERFILE_TEMPLATE)
    return project_root


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a quant research project scaffold")
    parser.add_argument("--root", required=True, help="New or empty directory to create")
    args = parser.parse_args()
    project_root = create_structure(args.root)
    print(f"Scaffold created at {project_root}")


if __name__ == "__main__":
    main()
